### ISSUE TITLE
Installation error.

### ISSUE THREAD

**Issue by chkimmmmm** [gmihaila/ml_things#10]
Hello, I tried to re-build your GPT2 classifcation page.

But I found an issue.

Maybe some of your requirement is outdated?

ERROR: Could not find a version that satisfies the requirement matplotlib>=3.4.0 (from ml-things)
ERROR: No matching distribution found for matplotlib>=3.4.0

I got this issue.

Thank you.

**Comment by lucastliu** [comment]
Setup.py matplot lib dependency problem. Easiest fix is to just go to setup.py and change "matplotlib>=3.4.0" to "matplotlib"
