### ISSUE TITLE
Wrong link in gpt2_finetune_classification.ipynb

### ISSUE THREAD

**Issue by lukaskuhn-lku** [gmihaila/ml_things#11]
The link to the google colab notebook in _gpt2_finetune_classification.ipynb_ does not lead to the right notebook. It currently leads to _https://colab.research.google.com/github/gmihaila/ml_things/blob/master/notebooks/pytorch/pretrain_transformers_pytorch.ipynb_ and should be changed to _https://colab.research.google.com/github/gmihaila/ml_things/blob/master/notebooks/pytorch/gpt2_finetune_classification.ipynb_

**Comment by gmihaila** [comment]
Hi @lukaskuhn-lku ! Great catch! Thank you for your contribution! It's now fixed.
