### ISSUE TITLE
pre-train

### ISSUE THREAD

**Issue by shainaraza** [gmihaila/ml_things#18]
Hi @gmihaila thanks for this splendid library.
Just have a quick question regarding pre-training from scratch, is it possible using a single system. I don't have much data to pre-train.
Any suggestions.
thanks

**Comment by gmihaila** [comment]
@shainaraza what do you mean by single system?

**Comment by shainaraza** [comment]
yes @gmihaila I have Colab just and want to train model on 100000 of publications data (papers and their text).

**Comment by gmihaila** [comment]
@shainaraza Yes, you should be able to use a Colab to pre-train from scratch. Make sure to use a GPU. I did it myself several times.
As for the data size, I'm not sure how many lines of text will 100,000 publications take but I'm pretty sure it should be able to handle it as long as it can fit in ram.
