### ISSUE TITLE
Longformer issue

### ISSUE THREAD

**Issue by shainaraza** [gmihaila/ml_things#5]
Hi @gmihaila 
The fine-tuning notebook works very well, but when I use a sample size of larger than 100 records, the longformer notebook shows strange messages.
![image](https://user-images.githubusercontent.com/32249936/100118183-99072180-2e43-11eb-8d3e-7f36395d9cf6.png)

this has nothing to do with the ML-Things library fix text(), even if I dont use it, I still get some error, upong reducing the sample size, it works fine,
any suggestions please

**Comment by gmihaila** [comment]
@shainaraza 
Make sure that your text data has the right format. In the error it looks like text is a float and it's trying to get the length of a float. I would try to find the exact sample where the error occurs and see how it looks like maybe it's a weird format.

The fix text shouldn't be any issues. It only fixes any weird characters that you might have in the text data.

If you're ok with reducing the sample size I would recommend doing that if it fixes the error.

**Comment by shainaraza** [comment]
@gmihaila 
thanks, you give me super advise, really grateful.
I was able to resolve,
the reason was that I am using more than text as the input, it gave me list of list with texts.append(), I flattened it to one list now its working.

great help from you on this notebook
best
