### ISSUE TITLE
Making use of saved model

### ISSUE THREAD

**Issue by Ghani-25** [gmihaila/ml_things#8]
Hello,

i am using pretrain_transformers_pytorch.ipynb, I have successfully followed all steps, my question is how to reload the pretrain_bert saved model to make us of it?

thank you

**Comment by gmihaila** [comment]
Hi @Ghani-25, Thank you for your question!

You will need to save the model at the end of the notebook. Next when you use in a different place just load it using the path where you saved the model.

Here is how you do it in PyTorch: https://pytorch.org/tutorials/beginner/saving_loading_models.html
