### ISSUE TITLE
How to score new data after fine tuning

### ISSUE THREAD

**Issue by sanjayb678** [gmihaila/ml_things#9]
I use the notebook to fine tune a custom dataset for a multi class classification task. How do I use the fine tuned model on new data to label. Thanks.

**Comment by gmihaila** [comment]
Hi @sanjayb678 and Thank you for your question!

You will need to save the model at the end of the code. Next, when you use it in a different code you just load it form the path you saved it.

Here is how you do it in PyTorch: https://pytorch.org/tutorials/beginner/saving_loading_models.html
